Name:           ros-indigo-srdfdom
Version:        0.3.2
Release:        0%{?dist}
Summary:        ROS srdfdom package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/srdfdom
Source0:        %{name}-%{version}.tar.gz

Requires:       boost-devel
Requires:       console-bridge-devel
Requires:       ros-indigo-urdfdom-py
Requires:       tinyxml-devel
Requires:       urdfdom-headers-devel
BuildRequires:  boost-devel
BuildRequires:  console-bridge-devel
BuildRequires:  ros-indigo-catkin
BuildRequires:  ros-indigo-cmake-modules
BuildRequires:  ros-indigo-rostest
BuildRequires:  ros-indigo-urdfdom-py
BuildRequires:  tinyxml-devel
BuildRequires:  urdfdom-headers-devel

%description
Parser for Semantic Robot Description Format (SRDF).

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Thu Aug 25 2016 Dave Coleman <dave@dav.ee> - 0.3.2-0
- Autogenerated by Bloom

* Mon Aug 01 2016 Ioan Sucan <isucan@willowgarage.com> - 0.3.1-0
- Autogenerated by Bloom

* Tue Jun 16 2015 Ioan Sucan <isucan@willowgarage.com> - 0.3.0-0
- Autogenerated by Bloom

